- name: Pull nginx image
  community.docker.docker_image:
    name: nginx:latest
    source: pull

- name: Copy nginx.conf file
  template:
    src: /Users/lewisan/Desktop/COMP90024/A2/awesome-backend/playbook/deploy/nginx.conf.j2
    dest: /home/ubuntu/nginx.conf

- name: Run load balancer
  community.docker.docker_container:
    name: nginx-balancer
    image: nginx:latest
    state: started
    recreate: yes
    pull: false
    published_ports:
      - "82:80"
    networks:
      - name: demo-network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf