- name: Create Docker volume for CouchDB data
  docker_volume:
    name: couchdb-data

- name: Stop and remove existing CouchDB container
  docker_container:
    name: couchdb
    state: absent
    force_kill: yes

- name: Deploy CouchDB container with mounted volume
  docker_container:
    name: couchdb
    image: couchdb:latest
    state: started
    pull: yes
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: "{{db_user}}"
      COUCHDB_PASSWORD: "{{db_password}}"
      COUCHDB_SECRET: "{{ db_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ db_cookie }}\" -name \"couchdb@{{inventory_hostname}}\""
    volumes:
      - "couchdb-data:/opt/couchdb/data"